### ISSUE TITLE
Volatile=true

### ISSUE THREAD

**Issue by dmtrs** [wekaco/samplernn-pytorch#12]
- https://pytorch.org/docs/0.3.1/autograd.html#variable

**Comment by blibliki** [comment]
https://discuss.pytorch.org/t/volatile-now-has-no-effect-use-with-torch-no-grad-instead/26656/9

**Comment by dmtrs** [comment]
Resolved in current nightly commit https://github.com/wekaco/samplernn-pytorch/commit/be702409b7ce58d487a820493dfb549321903d6e
